version: '3'

services:
  nginx-container:
    image: nginx:latest
    labels:
      - io.project-name=repo-nginx-test-2
    container_name: nginx-docker
    networks:
      - my_network
    ports:
      - "${PORT:-81}:80"
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
