version: '3.7'

services:
  nginx-container:
    image: nginx:latest
    labels:
      - io.project-name=repo-nginx-test-1
    container_name: nginx-docker
    ports:
      - "${PORT:-81}:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
