version: '3.1'
services:
  webapp:
    image: nginx:1.20.1
    restart: always
    labels:
      - "custom-version=2"
    ports:
      - "${PORT:-3002}:80"
    volumes:
      - ./static:/usr/share/nginx/html
